/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delivery;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author henri
 */
public class delivery extends javax.swing.JFrame {

    public static String pizza, tamanhopizza, precoPizza, lanche, precoLanche, adicional, porcao, tamanhoporcao, precoPorcao, tipoEntrega = null, pgto;
    public static int total, totalFinal;
    ArrayList<String> info = new ArrayList<String>();
    ArrayList<String> adicionaisPorc = new ArrayList<String>();

    public delivery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        batata = new javax.swing.JCheckBox();
        fpassarinho = new javax.swing.JCheckBox();
        isca = new javax.swing.JCheckBox();
        mandioca = new javax.swing.JCheckBox();
        file = new javax.swing.JCheckBox();
        bolinha = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addBacon = new javax.swing.JCheckBox();
        addQueijo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        contato = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        tamPorc = new javax.swing.JComboBox<>();
        dinheiro = new javax.swing.JCheckBox();
        cartao = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        delivery = new javax.swing.JCheckBox();
        retirada = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        taxaEntrega = new javax.swing.JTextField();
        valPedido = new javax.swing.JTextField();
        valTotal = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tamPizza = new javax.swing.JComboBox<>();
        frangop = new javax.swing.JCheckBox();
        queijop = new javax.swing.JCheckBox();
        atump = new javax.swing.JCheckBox();
        romeup = new javax.swing.JCheckBox();
        chocp = new javax.swing.JCheckBox();
        napop = new javax.swing.JCheckBox();
        portp = new javax.swing.JCheckBox();
        ctbone = new javax.swing.JCheckBox();
        csalada = new javax.swing.JCheckBox();
        cbacon = new javax.swing.JCheckBox();
        cegg = new javax.swing.JCheckBox();
        cfrango = new javax.swing.JCheckBox();
        cvegan = new javax.swing.JCheckBox();
        ccheddar = new javax.swing.JCheckBox();
        cbarbecue = new javax.swing.JCheckBox();
        calabresap = new javax.swing.JCheckBox();
        calabresaPorc = new javax.swing.JCheckBox();
        salvarpizza = new javax.swing.JButton();
        salvarlanche = new javax.swing.JButton();
        salvarporcao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        painel = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        addBaconPorc = new javax.swing.JCheckBox();
        addCheddarPorc = new javax.swing.JCheckBox();
        addQueijoPorc = new javax.swing.JCheckBox();
        limpar = new javax.swing.JButton();
        complemento = new javax.swing.JTextField();
        JtextField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Adicionais");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Pizzas");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Porções");

        batata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        batata.setText("Batata Frita");
        batata.setAutoscrolls(true);
        batata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batataActionPerformed(evt);
            }
        });

        fpassarinho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fpassarinho.setText("Frango a Passarinho");
        fpassarinho.setAutoscrolls(true);
        fpassarinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpassarinhoActionPerformed(evt);
            }
        });

        isca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        isca.setText("Iscas de Peixe");
        isca.setAutoscrolls(true);
        isca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iscaActionPerformed(evt);
            }
        });

        mandioca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mandioca.setText("Mandioca Frita");
        mandioca.setAutoscrolls(true);
        mandioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandiocaActionPerformed(evt);
            }
        });

        file.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        file.setText("Filé a Palito");
        file.setAutoscrolls(true);
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });

        bolinha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bolinha.setText("Bolinhas de Queijo");
        bolinha.setAutoscrolls(true);
        bolinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolinhaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Tamanho Porção");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Lanches");

        addBacon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addBacon.setText("Bacon - R$4,00");
        addBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBaconActionPerformed(evt);
            }
        });

        addQueijo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addQueijo.setText("Queijo - R$4,00");
        addQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQueijoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Informações");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Entrega");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        contato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Contato");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Rua");

        rua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Bairro");

        bairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Número");

        numero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Cidade");

        cidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Estado");

        estado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("CEP");

        cep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tamPorc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tamPorc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Pequena - R$14,00", "Média - R$18,00", "Grande - R$22,00", "Gigante - R$27,00" }));
        tamPorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamPorcActionPerformed(evt);
            }
        });

        dinheiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dinheiro.setText("Dinheiro");
        dinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiroActionPerformed(evt);
            }
        });

        cartao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cartao.setText("Cartão");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("Pagamento");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setText("Total");

        delivery.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        delivery.setText("Delivery -  R$7,00");
        delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryActionPerformed(evt);
            }
        });

        retirada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        retirada.setText("Retirada no Balcão");
        retirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiradaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Valor do Pedido");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Taxa de Entrega");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Valor Total");

        taxaEntrega.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taxaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaEntregaActionPerformed(evt);
            }
        });

        valPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valPedidoActionPerformed(evt);
            }
        });

        valTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valTotalActionPerformed(evt);
            }
        });

        confirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmar.setText("Confirmar Pedido");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setText("Pedido");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel25.setText("Sabores");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel26.setText("Tamanho");

        tamPizza.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tamPizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Pequena - R$34,00", "Média - R$38,00", "Grande - R$44,00", "Gigante - R$52,00" }));
        tamPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamPizzaActionPerformed(evt);
            }
        });

        frangop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frangop.setText("Frango c/ Catupiry");
        frangop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frangopActionPerformed(evt);
            }
        });

        queijop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        queijop.setText("4 Queijos");
        queijop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queijopActionPerformed(evt);
            }
        });

        atump.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atump.setText("Atum");
        atump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atumpActionPerformed(evt);
            }
        });

        romeup.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        romeup.setText("Romeu e Julieta");
        romeup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romeupActionPerformed(evt);
            }
        });

        chocp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chocp.setText("Chocolate");
        chocp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocpActionPerformed(evt);
            }
        });

        napop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        napop.setText("Napolitana");
        napop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                napopActionPerformed(evt);
            }
        });

        portp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        portp.setText("Portuguesa");
        portp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portpActionPerformed(evt);
            }
        });

        ctbone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctbone.setText("Cheese T-Bone  - R$28,00");
        ctbone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctboneActionPerformed(evt);
            }
        });

        csalada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        csalada.setText("Cheese Salada - R$20,00");
        csalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csaladaActionPerformed(evt);
            }
        });

        cbacon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbacon.setText("Cheese Bacon - R$22,00");
        cbacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbaconActionPerformed(evt);
            }
        });

        cegg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cegg.setText("Cheese Egg - R$22,00");
        cegg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceggActionPerformed(evt);
            }
        });

        cfrango.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cfrango.setText("Cheese Frango - R$22,00");
        cfrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfrangoActionPerformed(evt);
            }
        });

        cvegan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cvegan.setText("Cheese Vegan - R$25,00");
        cvegan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cveganActionPerformed(evt);
            }
        });

        ccheddar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ccheddar.setText("Cheese Cheddar - R$24,00");
        ccheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccheddarActionPerformed(evt);
            }
        });

        cbarbecue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbarbecue.setText("Cheese Barbecue - R$25,00");
        cbarbecue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbarbecueActionPerformed(evt);
            }
        });

        calabresap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calabresap.setText("Calabresa");
        calabresap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calabresapActionPerformed(evt);
            }
        });

        calabresaPorc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calabresaPorc.setText("Calabresa Frita");
        calabresaPorc.setAutoscrolls(true);
        calabresaPorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calabresaPorcActionPerformed(evt);
            }
        });

        salvarpizza.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salvarpizza.setText("Salvar Pedido Pizza");
        salvarpizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarpizzaActionPerformed(evt);
            }
        });

        salvarlanche.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salvarlanche.setText("Salvar Pedido Lanche");
        salvarlanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarlancheActionPerformed(evt);
            }
        });

        salvarporcao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salvarporcao.setText("Salvar Pedido Porção");
        salvarporcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarporcaoActionPerformed(evt);
            }
        });

        painel.setEditable(false);
        jScrollPane1.setViewportView(painel);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Adicionais");

        addBaconPorc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addBaconPorc.setText("Bacon ");
        addBaconPorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBaconPorcActionPerformed(evt);
            }
        });

        addCheddarPorc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addCheddarPorc.setText("Cheddar");
        addCheddarPorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCheddarPorcActionPerformed(evt);
            }
        });

        addQueijoPorc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addQueijoPorc.setText("Queijo");

        limpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        limpar.setText("Limpar Pedidos");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        complemento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        JtextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JtextField.setText("Complemento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(retirada)
                                    .addComponent(delivery))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel23))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(valPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                            .addComponent(taxaEntrega)
                                            .addComponent(valTotal))))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dinheiro)
                                    .addComponent(cartao)
                                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(25, 25, 25)
                                        .addComponent(bairro))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(41, 41, 41)
                                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JtextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(complemento)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salvarpizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(frangop)
                            .addComponent(calabresap)
                            .addComponent(jLabel3)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(napop)
                            .addComponent(portp)
                            .addComponent(romeup)
                            .addComponent(chocp)
                            .addComponent(atump)
                            .addComponent(queijop)
                            .addComponent(jLabel8)
                            .addComponent(tamPizza, 0, 0, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cegg)
                            .addComponent(jLabel6)
                            .addComponent(csalada)
                            .addComponent(cbacon)
                            .addComponent(cfrango)
                            .addComponent(cvegan)
                            .addComponent(ccheddar)
                            .addComponent(ctbone)
                            .addComponent(jLabel2)
                            .addComponent(addBacon)
                            .addComponent(addQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbarbecue)
                            .addComponent(salvarlanche, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addBaconPorc)
                                    .addComponent(addCheddarPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addQueijoPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(isca)
                                    .addComponent(calabresaPorc)
                                    .addComponent(bolinha)
                                    .addComponent(file)
                                    .addComponent(mandioca)
                                    .addComponent(batata)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tamPorc, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                        .addComponent(fpassarinho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(limpar)))
                            .addComponent(salvarporcao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contato, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addGap(10, 10, 10)
                                .addComponent(tamPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)
                                .addGap(13, 13, 13)
                                .addComponent(calabresap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frangop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atump)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(queijop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(napop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chocp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(romeup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salvarpizza))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(csalada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbacon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cegg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cfrango, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cvegan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ccheddar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbarbecue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctbone)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addBacon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addQueijo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salvarlanche)))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tamPorc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mandioca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(file)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bolinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calabresaPorc)
                        .addGap(2, 2, 2)
                        .addComponent(fpassarinho)
                        .addGap(2, 2, 2)
                        .addComponent(isca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addQueijoPorc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCheddarPorc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBaconPorc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvarporcao)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(JtextField)
                    .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retirada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delivery))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(valPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(dinheiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cartao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarpizzaActionPerformed
        int selecao = tamPizza.getSelectedIndex();
        if (selecao == 0) {
            pizza = null;
            tamanhopizza = null;
            precoPizza = null;
        }
        
        if (selecao != 0 && pizza != null) {
            if (selecao == 1) {
                total += 34;
            }
            if (selecao == 2) {
                total += 38;
            }
            if (selecao == 3) {
                total += 44;
            }
            if (selecao == 4) {
                total += 52;
            }

            info.add("1 Pizza " + pizza + ", " + tamanhopizza + " - " + precoPizza + "\n");
            painel.setText(info.toString());

        }
        totalFinal = total;
        pizza = null;
        tamanhopizza = null;
        precoPizza = null;
        calabresap.setSelected(false);
        frangop.setSelected(false);
        atump.setSelected(false);
        queijop.setSelected(false);
        portp.setSelected(false);
        napop.setSelected(false);
        chocp.setSelected(false);
        romeup.setSelected(false);
        tamPizza.setSelectedIndex(0);
        valPedido.setText(Double.toString(total));
        valTotal.setText(Double.toString(totalFinal));
    }//GEN-LAST:event_salvarpizzaActionPerformed

    private void calabresapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calabresapActionPerformed
        frangop.setSelected(false);
        atump.setSelected(false);
        queijop.setSelected(false);
        portp.setSelected(false);
        napop.setSelected(false);
        chocp.setSelected(false);
        romeup.setSelected(false);
        pizza = "Calabresa";
    }//GEN-LAST:event_calabresapActionPerformed

    private void cbaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbaconActionPerformed
        csalada.setSelected(false);
        cegg.setSelected(false);
        cfrango.setSelected(false);
        cvegan.setSelected(false);
        ccheddar.setSelected(false);
        cbarbecue.setSelected(false);
        ctbone.setSelected(false);
        lanche = "Cheese Bacon";
        precoLanche = "R$22,00";
    }//GEN-LAST:event_cbaconActionPerformed

    private void portpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portpActionPerformed
        calabresap.setSelected(false);
        frangop.setSelected(false);
        atump.setSelected(false);
        queijop.setSelected(false);
        napop.setSelected(false);
        chocp.setSelected(false);
        romeup.setSelected(false);
        pizza = "Portuguesa";
    }//GEN-LAST:event_portpActionPerformed

    private void napopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_napopActionPerformed
        calabresap.setSelected(false);
        frangop.setSelected(false);
        atump.setSelected(false);
        queijop.setSelected(false);
        portp.setSelected(false);
        chocp.setSelected(false);
        romeup.setSelected(false);
        pizza = "Napolitana";
    }//GEN-LAST:event_napopActionPerformed

    private void chocpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocpActionPerformed
        calabresap.setSelected(false);
        frangop.setSelected(false);
        atump.setSelected(false);
        queijop.setSelected(false);
        portp.setSelected(false);
        napop.setSelected(false);
        romeup.setSelected(false);
        pizza = "Chocolate";
    }//GEN-LAST:event_chocpActionPerformed

    private void romeupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romeupActionPerformed
        calabresap.setSelected(false);
        frangop.setSelected(false);
        atump.setSelected(false);
        queijop.setSelected(false);
        portp.setSelected(false);
        napop.setSelected(false);
        chocp.setSelected(false);
        pizza = "Romeu e Julieta";
    }//GEN-LAST:event_romeupActionPerformed

    private void atumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atumpActionPerformed
        calabresap.setSelected(false);
        frangop.setSelected(false);
        queijop.setSelected(false);
        portp.setSelected(false);
        napop.setSelected(false);
        chocp.setSelected(false);
        romeup.setSelected(false);
        pizza = "Atum";
    }//GEN-LAST:event_atumpActionPerformed

    private void queijopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queijopActionPerformed
        calabresap.setSelected(false);
        frangop.setSelected(false);
        atump.setSelected(false);
        portp.setSelected(false);
        napop.setSelected(false);
        chocp.setSelected(false);
        romeup.setSelected(false);
        pizza = "4 Queijos";
    }//GEN-LAST:event_queijopActionPerformed

    private void frangopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frangopActionPerformed
        calabresap.setSelected(false);
        atump.setSelected(false);
        queijop.setSelected(false);
        portp.setSelected(false);
        napop.setSelected(false);
        chocp.setSelected(false);
        romeup.setSelected(false);
        pizza = "Frango c/ Catupiry";
    }//GEN-LAST:event_frangopActionPerformed

    private void tamPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamPizzaActionPerformed
        int selecao = tamPizza.getSelectedIndex();
        if (selecao == 1) {
            tamanhopizza = "Pequena";
            precoPizza = "R$34,00";
        }
        if (selecao == 2) {
            tamanhopizza = "Média";
            precoPizza = "R$38,00";
        }
        if (selecao == 3) {
            tamanhopizza = "Grande";
            precoPizza = "R$44,00";
        }
        if (selecao == 4) {
            tamanhopizza = "Gigante";
            precoPizza = "R$52,00";
        }
    }//GEN-LAST:event_tamPizzaActionPerformed

    private void valTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valTotalActionPerformed

    }//GEN-LAST:event_valTotalActionPerformed

    private void valPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valPedidoActionPerformed

    }//GEN-LAST:event_valPedidoActionPerformed

    private void taxaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaEntregaActionPerformed

    }//GEN-LAST:event_taxaEntregaActionPerformed

    private void retiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiradaActionPerformed
        if (delivery.isSelected()) {
            totalFinal = totalFinal - 7;
        }
        if (retirada.isSelected()) {
            delivery.setSelected(false);
            taxaEntrega.setText("0.0");
            valTotal.setText(Double.toString(totalFinal));
            tipoEntrega = "Retirada no Balcão";
        }
    }//GEN-LAST:event_retiradaActionPerformed

    private void deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryActionPerformed
        if (delivery.isSelected()) {
            retirada.setSelected(false);
            taxaEntrega.setText("7.0");
            totalFinal = total + 7;
            valTotal.setText(Double.toString(totalFinal));
            tipoEntrega = "Delivery R$7,00";
        }
    }//GEN-LAST:event_deliveryActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed

    private void csaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csaladaActionPerformed
        cbacon.setSelected(false);
        cegg.setSelected(false);
        cfrango.setSelected(false);
        cvegan.setSelected(false);
        ccheddar.setSelected(false);
        cbarbecue.setSelected(false);
        ctbone.setSelected(false);
        lanche = "Cheese Salada";
        precoLanche = "R$20,00";
    }//GEN-LAST:event_csaladaActionPerformed

    private void ceggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceggActionPerformed
        csalada.setSelected(false);
        cbacon.setSelected(false);
        cfrango.setSelected(false);
        cvegan.setSelected(false);
        ccheddar.setSelected(false);
        cbarbecue.setSelected(false);
        ctbone.setSelected(false);
        lanche = "Cheese Egg";
        precoLanche = "R$22,00";
    }//GEN-LAST:event_ceggActionPerformed

    private void cfrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfrangoActionPerformed
        csalada.setSelected(false);
        cbacon.setSelected(false);
        cegg.setSelected(false);
        cvegan.setSelected(false);
        ccheddar.setSelected(false);
        cbarbecue.setSelected(false);
        ctbone.setSelected(false);
        lanche = "Cheese Frango";
        precoLanche = "R$22,00";
    }//GEN-LAST:event_cfrangoActionPerformed

    private void cveganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cveganActionPerformed
        csalada.setSelected(false);
        cbacon.setSelected(false);
        cegg.setSelected(false);
        cfrango.setSelected(false);
        ccheddar.setSelected(false);
        cbarbecue.setSelected(false);
        ctbone.setSelected(false);
        lanche = "Cheese Vegan";
        precoLanche = "R$25,00";
    }//GEN-LAST:event_cveganActionPerformed

    private void ccheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccheddarActionPerformed
        csalada.setSelected(false);
        cbacon.setSelected(false);
        cegg.setSelected(false);
        cfrango.setSelected(false);
        cvegan.setSelected(false);
        cbarbecue.setSelected(false);
        ctbone.setSelected(false);
        lanche = "Cheese Cheddar";
        precoLanche = "R$24,00";
    }//GEN-LAST:event_ccheddarActionPerformed

    private void cbarbecueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbarbecueActionPerformed
        csalada.setSelected(false);
        cbacon.setSelected(false);
        cegg.setSelected(false);
        cfrango.setSelected(false);
        cvegan.setSelected(false);
        ccheddar.setSelected(false);
        ctbone.setSelected(false);
        lanche = "Cheese Barbecue";
        precoLanche = "R$25,00";
    }//GEN-LAST:event_cbarbecueActionPerformed

    private void ctboneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctboneActionPerformed
        csalada.setSelected(false);
        cbacon.setSelected(false);
        cegg.setSelected(false);
        cfrango.setSelected(false);
        cvegan.setSelected(false);
        ccheddar.setSelected(false);
        cbarbecue.setSelected(false);
        lanche = "Cheese T-Bone";
        precoLanche = "R$28,00";
    }//GEN-LAST:event_ctboneActionPerformed

    private void salvarlancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarlancheActionPerformed
        if (addBacon.isSelected() || addQueijo.isSelected()) {
            if (addBacon.isSelected() && lanche != null) {
                total += 4;
                adicional = " + (Adicional de Bacon R$4,00)";
            }
            if (addQueijo.isSelected() && lanche != null) {
                total += 4;
                adicional = " + (Adicional de Queijo R$4,00)";
            }
            if (addBacon.isSelected() && addQueijo.isSelected() && lanche != null) {
                adicional = " + (Adicional de Queijo e Bacon R$8,00)";
            }
        }

        if (lanche != null && precoLanche != null && adicional == null) {
            info.add("1 " + lanche + " - " + precoLanche + "\n");
            painel.setText(info.toString());
        }
        if (lanche != null && precoLanche != null && adicional != null) {
            info.add("1 " + lanche + " - " + precoLanche + adicional + "\n");
            painel.setText(info.toString());
        }

        if (csalada.isSelected()) {
            total += 20;
        }
        if (cbacon.isSelected()) {
            total += 22;
        }
        if (cegg.isSelected()) {
            total += 22;
        }
        if (cfrango.isSelected()) {
            total += 22;
        }
        if (cvegan.isSelected()) {
            total += 25;
        }
        if (ccheddar.isSelected()) {
            total += 24;
        }
        if (cbarbecue.isSelected()) {
            total += 25;
        }
        if (ctbone.isSelected()) {
            total += 28;
        }

        lanche = null;
        precoLanche = null;
        addBacon.setSelected(false);
        addQueijo.setSelected(false);
        csalada.setSelected(false);
        cbacon.setSelected(false);
        cegg.setSelected(false);
        cfrango.setSelected(false);
        cvegan.setSelected(false);
        ccheddar.setSelected(false);
        cbarbecue.setSelected(false);
        ctbone.setSelected(false);
        totalFinal = total;
        valPedido.setText(Double.toString(total));
        valTotal.setText(Double.toString(totalFinal));
        
    }//GEN-LAST:event_salvarlancheActionPerformed

    private void addBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBaconActionPerformed

    }//GEN-LAST:event_addBaconActionPerformed

    private void addBaconPorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBaconPorcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBaconPorcActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        info.clear();
        total = 0;
        totalFinal = 0;
        taxaEntrega.setText("");
        valPedido.setText("");
        valTotal.setText("");
        painel.setText("");
        tamPizza.setSelectedIndex(0);
        tamPorc.setSelectedIndex(0);
        delivery.setSelected(false);
        retirada.setSelected(false);
        addBacon.setSelected(false);
        addQueijo.setSelected(false);
        csalada.setSelected(false);
        cbacon.setSelected(false);
        cegg.setSelected(false);
        cfrango.setSelected(false);
        cvegan.setSelected(false);
        ccheddar.setSelected(false);
        cbarbecue.setSelected(false);
        ctbone.setSelected(false);
        addQueijoPorc.setSelected(false);
        addBaconPorc.setSelected(false);
        addCheddarPorc.setSelected(false);
        batata.setSelected(false);
        mandioca.setSelected(false);
        file.setSelected(false);
        bolinha.setSelected(false);
        calabresaPorc.setSelected(false);
        fpassarinho.setSelected(false);
        isca.setSelected(false);
        calabresap.setSelected(false);
        frangop.setSelected(false);
        atump.setSelected(false);
        queijop.setSelected(false);
        portp.setSelected(false);
        napop.setSelected(false);
        chocp.setSelected(false);
        romeup.setSelected(false);
    }//GEN-LAST:event_limparActionPerformed

    private void tamPorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamPorcActionPerformed
        int selecao = tamPorc.getSelectedIndex();

        if (selecao == 0) {
            addQueijoPorc.setText("Queijo");
            addCheddarPorc.setText("Cheddar");
            addBaconPorc.setText("Bacon");
        }
        if (selecao == 1) {
            addQueijoPorc.setText("Queijo - R$5,00");
            addCheddarPorc.setText("Cheddar - R$6,00");
            addBaconPorc.setText("Bacon - R$7,00");
        }
        if (selecao == 2) {
            addQueijoPorc.setText("Queijo - R$6,00");
            addCheddarPorc.setText("Cheddar - R$7,00");
            addBaconPorc.setText("Bacon - R$8,00");
        }
        if (selecao == 3) {
            addQueijoPorc.setText("Queijo - R$7,00");
            addCheddarPorc.setText("Cheddar - R$8,00");
            addBaconPorc.setText("Bacon - R$9,00");
        }
        if (selecao == 4) {
            addQueijoPorc.setText("Queijo - R$9,00");
            addCheddarPorc.setText("Cheddar - R$10,00");
            addBaconPorc.setText("Bacon - R$11,00");
        }
    }//GEN-LAST:event_tamPorcActionPerformed

    private void salvarporcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarporcaoActionPerformed
        int selecao = tamPorc.getSelectedIndex();
        int aux = 0;

        if (selecao == 0) {
            porcao = null;
            tamanhoporcao = null;
            precoPorcao = null;
        }
        if (porcao != null) {
            if (selecao == 1) {
                total += 14;
                tamanhoporcao = "Pequena";
                precoPorcao = "R$14,00";
                if (addQueijoPorc.isSelected() || addCheddarPorc.isSelected() || addBaconPorc.isSelected()) {
                    if (addQueijoPorc.isSelected()) {
                        total += 5;
                        adicional = " (Adicional de Queijo P R$5,00) ";
                        adicionaisPorc.add(adicional);
                    }
                    if (addCheddarPorc.isSelected()) {
                        total += 6;
                        adicional = " (Adicional de Cheddar P R$6,00) ";
                        adicionaisPorc.add(adicional);
                    }
                    if (addBaconPorc.isSelected()) {
                        total += 7;
                        adicional = " (Adicional de Bacon P R$7,00) ";
                        adicionaisPorc.add(adicional);
                    }
                }
                info.add("1 Porção de " + porcao + ", " + tamanhoporcao + " - " + precoPorcao + adicionaisPorc.toString() + "\n");
                painel.setText(info.toString());
            }

            if (selecao == 2) {
                total += 18;
                tamanhoporcao = "Média";
                precoPorcao = "R$18,00";
                if (addQueijoPorc.isSelected() || addCheddarPorc.isSelected() || addBaconPorc.isSelected()) {
                    if (addQueijoPorc.isSelected()) {
                        total += 6;
                        adicional = " (Adicional de Queijo M R$6,00)";
                        adicionaisPorc.add(adicional);
                    }
                    if (addCheddarPorc.isSelected()) {
                        total += 7;
                        adicional = " (Adicional de Cheddar M R$7,00)";
                        adicionaisPorc.add(adicional);
                    }
                    if (addBaconPorc.isSelected()) {
                        total += 8;
                        adicional = " (Adicional de Bacon M R$8,00)";
                        adicionaisPorc.add(adicional);
                    }
                }
                info.add("1 Porção de " + porcao + ", " + tamanhoporcao + " - " + precoPorcao + adicionaisPorc.toString() + "\n");
                painel.setText(info.toString());
            }

            if (selecao == 3) {
                total += 22;
                tamanhoporcao = "Grande";
                precoPorcao = "R$22,00";
                if (addQueijoPorc.isSelected() || addCheddarPorc.isSelected() || addBaconPorc.isSelected()) {
                    if (addQueijoPorc.isSelected()) {
                        total += 7;
                        adicional = " (Adicional de Queijo G R$7,00)";
                        adicionaisPorc.add(adicional);
                    }
                    if (addCheddarPorc.isSelected()) {
                        total += 8;
                        adicional = " (Adicional de Cheddar G R$8,00)";
                        adicionaisPorc.add(adicional);
                    }
                    if (addBaconPorc.isSelected()) {
                        total += 9;
                        adicional = " (Adicional de Bacon G R$9,00)";
                        adicionaisPorc.add(adicional);
                    }
                }
                info.add("1 Porção de" + porcao + ", " + tamanhoporcao + " - " + precoPorcao + adicionaisPorc.toString() + "\n");
                painel.setText(info.toString());
            }

            if (selecao == 4) {
                total += 27;
                tamanhoporcao = "Gigante";
                precoPorcao = "R$27,00";
                if (addQueijoPorc.isSelected() || addCheddarPorc.isSelected() || addBaconPorc.isSelected()) {
                    if (addQueijoPorc.isSelected()) {
                        total += 9;
                        adicional = " (Adicional de Queijo GG R$9,00)";
                        adicionaisPorc.add(adicional);
                    }
                    if (addCheddarPorc.isSelected()) {
                        total += 10;
                        adicional = " (Adicional de Cheddar GG R$10,00)";
                        adicionaisPorc.add(adicional);
                    }
                    if (addBaconPorc.isSelected()) {
                        total += 11;
                        adicional = " (Adicional de Bacon GG R$11,00)";
                        adicionaisPorc.add(adicional);
                    }
                }
                info.add("1 Porção de " + porcao + ", " + tamanhoporcao + " - " + precoPorcao + adicionaisPorc.toString() + "\n");
                painel.setText(info.toString());
            }
        }
        porcao = null;
        precoPorcao = null;
        tamanhoporcao = null;
        adicionaisPorc.clear();
        totalFinal = total;
        addQueijoPorc.setSelected(false);
        addBaconPorc.setSelected(false);
        addCheddarPorc.setSelected(false);
        batata.setSelected(false);
        mandioca.setSelected(false);
        file.setSelected(false);
        bolinha.setSelected(false);
        calabresaPorc.setSelected(false);
        fpassarinho.setSelected(false);
        isca.setSelected(false);
        tamPorc.setSelectedIndex(0);
        valPedido.setText(Double.toString(total));
        valTotal.setText(Double.toString(totalFinal));
    }//GEN-LAST:event_salvarporcaoActionPerformed

    private void batataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batataActionPerformed
        mandioca.setSelected(false);
        file.setSelected(false);
        bolinha.setSelected(false);
        calabresaPorc.setSelected(false);
        fpassarinho.setSelected(false);
        isca.setSelected(false);
        porcao = "Batata Frita";
    }//GEN-LAST:event_batataActionPerformed

    private void mandiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandiocaActionPerformed
        batata.setSelected(false);
        file.setSelected(false);
        bolinha.setSelected(false);
        calabresaPorc.setSelected(false);
        fpassarinho.setSelected(false);
        isca.setSelected(false);
        porcao = "Mandioca Frita";
    }//GEN-LAST:event_mandiocaActionPerformed

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        batata.setSelected(false);
        mandioca.setSelected(false);
        bolinha.setSelected(false);
        calabresaPorc.setSelected(false);
        fpassarinho.setSelected(false);
        isca.setSelected(false);
        porcao = "Filé a Palito";
    }//GEN-LAST:event_fileActionPerformed

    private void bolinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolinhaActionPerformed
        batata.setSelected(false);
        mandioca.setSelected(false);
        file.setSelected(false);
        calabresaPorc.setSelected(false);
        fpassarinho.setSelected(false);
        isca.setSelected(false);
        porcao = "Bolinha de Queijo";
    }//GEN-LAST:event_bolinhaActionPerformed

    private void calabresaPorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calabresaPorcActionPerformed
        batata.setSelected(false);
        mandioca.setSelected(false);
        file.setSelected(false);
        bolinha.setSelected(false);
        fpassarinho.setSelected(false);
        isca.setSelected(false);
        porcao = "Calabresa Frita";
    }//GEN-LAST:event_calabresaPorcActionPerformed

    private void fpassarinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpassarinhoActionPerformed
        batata.setSelected(false);
        mandioca.setSelected(false);
        file.setSelected(false);
        bolinha.setSelected(false);
        calabresaPorc.setSelected(false);
        isca.setSelected(false);
        porcao = "Frango a Passarinho";
    }//GEN-LAST:event_fpassarinhoActionPerformed

    private void iscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iscaActionPerformed
        batata.setSelected(false);
        mandioca.setSelected(false);
        file.setSelected(false);
        bolinha.setSelected(false);
        calabresaPorc.setSelected(false);
        fpassarinho.setSelected(false);
        porcao = "Isca de Peixe";
    }//GEN-LAST:event_iscaActionPerformed

    private void addCheddarPorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCheddarPorcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCheddarPorcActionPerformed

    private void addQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQueijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addQueijoActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        String complementoAux = complemento.getText();
  
        if(dinheiro.isSelected() || cartao.isSelected()){            
            if(dinheiro.isSelected()){
                pgto = "Dinheiro";
            }
            if(cartao.isSelected()){
                pgto = "Cartão";
            }      
            if(dinheiro.isSelected() && cartao.isSelected()){
                pgto = "Dinheiro e Cartão";
            }
        }
        
        if (complementoAux == null) {
            complementoAux = "";
        }

        String entrega = "Dados da Entrega: \n"
                + "Nome: " + nome.getText() + ", Contato: " + contato.getText() + "\n"
                + "Rua: " + rua.getText() + ", Número: " + numero.getText() + ", Bairro: " + bairro.getText() + ", Complemento: " + complementoAux + "\n"
                + "Cidade: " + cidade.getText() + ", Estado: " + estado.getText() + "\n"
                + "CEP: " + cep.getText() + "\n"
                + "Pedido: " + info.toString() + "\n"
                + tipoEntrega + "\n"
                + "Valor Pedido: R$" + total + "\n"
                + "Valor Total: R$" + totalFinal + "\n"
                + "Forma de Pagamento: " + pgto;

        byte[] buff = entrega.getBytes();

        try {
            RandomAccessFile raf = new RandomAccessFile("C:\\Users\\henri\\Desktop\\" + nome.getText() +".txt", "rw");           
            raf.write(buff);
            raf.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        dinheiro.setSelected(false);
        cartao.setSelected(false);
        delivery.setSelected(false);
        retirada.setSelected(false);
        nome.setText("");
        contato.setText("");
        rua.setText("");
        numero.setText("");
        bairro.setText("");
        complemento.setText("");
        cidade.setText("");
        estado.setText("");
        cep.setText("");
        info.clear();
        total = 0;
        totalFinal = 0;
        taxaEntrega.setText("");
        valPedido.setText("");
        valTotal.setText("");
        painel.setText("");
    }//GEN-LAST:event_confirmarActionPerformed

    private void dinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiroActionPerformed
        
    }//GEN-LAST:event_dinheiroActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delivery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JtextField;
    private javax.swing.JCheckBox addBacon;
    private javax.swing.JCheckBox addBaconPorc;
    private javax.swing.JCheckBox addCheddarPorc;
    private javax.swing.JCheckBox addQueijo;
    private javax.swing.JCheckBox addQueijoPorc;
    private javax.swing.JCheckBox atump;
    private javax.swing.JTextField bairro;
    private javax.swing.JCheckBox batata;
    private javax.swing.JCheckBox bolinha;
    private javax.swing.JCheckBox calabresaPorc;
    private javax.swing.JCheckBox calabresap;
    private javax.swing.JCheckBox cartao;
    private javax.swing.JCheckBox cbacon;
    private javax.swing.JCheckBox cbarbecue;
    private javax.swing.JCheckBox ccheddar;
    private javax.swing.JCheckBox cegg;
    private javax.swing.JTextField cep;
    private javax.swing.JCheckBox cfrango;
    private javax.swing.JCheckBox chocp;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField complemento;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField contato;
    private javax.swing.JCheckBox csalada;
    private javax.swing.JCheckBox ctbone;
    private javax.swing.JCheckBox cvegan;
    private javax.swing.JCheckBox delivery;
    private javax.swing.JCheckBox dinheiro;
    private javax.swing.JTextField estado;
    private javax.swing.JCheckBox file;
    private javax.swing.JCheckBox fpassarinho;
    private javax.swing.JCheckBox frangop;
    private javax.swing.JCheckBox isca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JCheckBox mandioca;
    private javax.swing.JCheckBox napop;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextPane painel;
    private javax.swing.JCheckBox portp;
    private javax.swing.JCheckBox queijop;
    private javax.swing.JCheckBox retirada;
    private javax.swing.JCheckBox romeup;
    private javax.swing.JTextField rua;
    private javax.swing.JButton salvarlanche;
    private javax.swing.JButton salvarpizza;
    private javax.swing.JButton salvarporcao;
    private javax.swing.JComboBox<String> tamPizza;
    private javax.swing.JComboBox<String> tamPorc;
    private javax.swing.JTextField taxaEntrega;
    private javax.swing.JTextField valPedido;
    private javax.swing.JTextField valTotal;
    // End of variables declaration//GEN-END:variables
}
